### ISSUE TITLE
hi, i think there were two more different methods for KD

### ISSUE THREAD

**Issue by yyht** [sseung0703/Knowledge_distillation_methods_wtih_Tensorflow#8]

**Comment by yyht** [comment]
Knowledge Representing: Efficient, Sparse Representation of Prior Knowledge
for Knowledge Distillation
KDGAN

I hope you could also implement those two different methods

**Comment by sseung0703** [comment]
Yes, new methods are always welcome. :) I'm eager to new distillation algorithms to add in my repository. However, because I have a limited time, I should choose an excellent method.
I'll check your recommendation, and if I think they are novel, I'll head to implement them.
Also, I think, there is stargazer to give me some passion. ;)
